### ISSUE TITLE
Leiningen has issues when pulling down support-1.1.0 as a dependency?

### ISSUE THREAD

**Issue by shailen1** [clojurewerkz/support#2]
Hi,

_upon doing a lein deps for my project.clj which is as below:_
``` clojure
(defproject dealer "1.0.0-SNAPSHOT"
  :description "FIXME: write description"
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.zeromq/cljzmq "0.1.4"]
                 [clojurewerkz/cassaforte "2.0.0"]
                 ;;[org.clojure/core.typed "0.3.3"]
                 ;;[org.clojure/data.json "0.2.6"]
                 ;;[org.clojure/core.match "0.3.0-alpha4"]
                 [clojurewerkz/elastisch "2.2.0-beta3"]]
                 ;;[clj-http "1.1.2"]
                 ;;[clojure-msgpack "1.1.0"]]
  :jvm-opts ["-Djava.library.path=/usr/local/lib"]
  :profiles {:main-dealer {:main dealer.dealer}
            :main-worker {:main dealer.worker}}
  :aot [:all]
  :plugins [[lein-typed "0.3.5"]]
  :core.typed {:check [adapters.core adapters.cassandra adapters.elasticsearch]})
```
 _I get the following error:_
```
Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file (NO_SOURCE_FILE:0)
	at clojure.lang.Compiler.eval(Compiler.java:5441)
	at clojure.lang.Compiler.eval(Compiler.java:5392)
	at clojure.core$eval.invoke(core.clj:2382)
	at clojure.main$eval_opt.invoke(main.clj:235)
	at clojure.main$initialize.invoke(main.clj:254)
	at clojure.main$script_opt.invoke(main.clj:270)
	at clojure.main$main.doInvoke(main.clj:354)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at clojure.lang.Var.invoke(Var.java:377)
	at clojure.lang.AFn.applyToHelper(AFn.java:172)
	at clojure.lang.Var.applyTo(Var.java:482)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
	at clojure.lang.LazySeq.sval(LazySeq.java:47)
	at clojure.lang.LazySeq.seq(LazySeq.java:56)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:560)
	at clojure.core$next.invoke(core.clj:61)
	at leiningen.deps$extract_native_deps.invoke(deps.clj:174)
	at leiningen.deps$deps.doInvoke(deps.clj:200)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.Var.invoke(Var.java:365)
	at clojure.lang.AFn.applyToHelper(AFn.java:161)
	at clojure.lang.Var.applyTo(Var.java:482)
	at clojure.core$apply.invoke(core.clj:542)
	at leiningen.core$apply_task.invoke(core.clj:262)
	at leiningen.core$_main.doInvoke(core.clj:329)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:161)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:542)
	at leiningen.core$_main.invoke(core.clj:332)
	at user$eval73.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.Compiler.eval(Compiler.java:5425)
	... 11 more
```
$unzip support-1.0.0.jar _gives me -_
```
Archive:  support-1.1.0.jar
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of support-1.1.0.jar or
        support-1.1.0.jar.zip, and cannot find support-1.1.0.jar.ZIP, period.
```

What could be going wrong? What am I missing?

This is on Ubuntu 14.04 with java 8; the same project has no issues bringing deps down on a mac.
$lein version
Leiningen 1.7.1 on Java 1.8.0_45 Java HotSpot(TM) 64-Bit Server VM

**Comment by shailen1** [comment]
thanks, figured it out: the downloaded support-1.1.0.jar was incomplete in the .m2 directory. just deleted it and reran lein deps was all :-)
